### ISSUE TITLE
Add a GitHub Actions to GitHub Marketplace 

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras#744]
### What is the version of your ORAS CLI

v0.16.0

### What would you like to be added?

ORAS is commonly used in CI/CD pipelines and workflows like GitHub Actions workflow. It would be easier for users to introduce and set up ORAS to their GitHub CI/CD workflows if ORAS has a GitHub Actions showcased on [GitHub Marketplace](https://github.com/marketplace?category=&query=&type=actions&verification=). 

Additionally, we can add the two most commonly-used CLI commands as examples in this GH actions for getting started:

- oras push
- oras attach

### Why is this needed for ORAS?

It will help users to easily introduce and set up ORAS to their GitHub CI/CD workflows and increase ORAS adoption.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by FeynmanZhou** [comment]
The potential use case for ORAS GitHub Actions:

```yml
# ORAS GitHub Actions

name: oras github actions

···

jobs:
  attach-SBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ORAS
        uses: oras-action/setup-oras@v1
      - env:                                  # optional (Configures GHCR by default. This is only used for using other registries)
          auth_token: ${{ secrets.auth_token }}
        uses: oras-action/login@v1
        with: 
          registry: sample-registry.io
          username: my-name

      - name: Push OCI artifact
        uses: oras-action/push@v1
        with: 
          repo: ${{repo:tag}}
          file: hi.txt

      - name: Attach SBOM
        uses: oras-action/attach@v2
        with: 
          artifact-type: ${{type}}
          repo: ${{repo:tag}}
          file: hi.txt
```

**Comment by shizhMSFT** [comment]
Based on @FeynmanZhou 's proposal, here's a more detailed one.
```yml
# ORAS GitHub Actions

name: oras github actions

···

jobs:
  attach-SBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ORAS
        uses: oras-project/oras-action/setup-oras@v1 # This allows running `oras` CLI directly
        with:
          oras-version: 1.0.0
      - name: Run ORAS
        run: oras version

      - uses: oras-project/oras-action/login@v1
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OCI artifact
        uses: oras-action/push@v1
        with: 
          artifact-type: application/example
          target: ghcr.io/${{ github.repository }}:example
          artifact: example.txt

      - name: Attach SBOM
        uses: oras-action/attach@v1
        with: 
          artifact-type: application/sbom
          subject: ghcr.io/${{ github.repository }}:example
          artifact: sbom.json
```

**Comment by FeynmanZhou** [comment]
@shizhMSFT Looks much better! We can adopt this proposal as a sample UX for ORAS GH actions. Shall we create a new repo to kick off this work? Is there any process we need to follow when setting up a new repo?

**Comment by shizhMSFT** [comment]
@FeynmanZhou After some [doc readings](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-publishing-actions), I found that

> Each repository must contain a single action.

if we want to publish to the GitHub Marketplace.

Therefore, it is reasonable to just keep the `setup-oras` action.
```yml
# ORAS GitHub Actions

name: oras github actions

···

jobs:
  attach-SBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1
        with:
          oras-version: 1.0.0
      - name: Run ORAS
        run: oras version
```
