### ISSUE TITLE
Gitlab job hanging when pushing sif with oras to container registry

### ISSUE THREAD

**Issue by rachelwaldon** [oras-project/oras#989]
### What happened in your environment?

Inside Gitlab CI job trying to push the sif with oras registry results in a 1 hour hanging job after the push command
```yaml
build-sif:
  stage: build
  timeout: 2h
  script:
    - apptainer version
    - pwd
    - whoami
    - echo $CI_REGISTRY_PASSWORD | apptainer remote login --username $CI_REGISTRY_USER --password-stdin docker://$CI_REGISTRY
    - apptainer build sst.sif sst.def
    - strace -f apptainer -d push sst.sif oras://${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest
  tags: [ ubuntu_vm ]
```

Here is the log 
[strace2.txt](https://github.com/oras-project/oras/files/11184457/strace2.txt)

### What did you expect to happen?

I expected the push command to be successful resulting in pushed image to Gitlab CI registry

### How can we reproduce it?

apptainer version 1.1.7

Running a GitLab job on a virtual machine Ubuntu 22.04 to build an apptainer sif image.

### What is the version of your ORAS CLI?

Version:        1.0.0
Go version:     go1.20.2
Git commit:     b58e7b910ca556973d111e9bd734a71baef03db2
Git tree state: clean

### What is your OS environment?

Ubuntu 22.04

### Are you willing to submit PRs to fix it?

- [ ] Yes, I am willing to fix it.
